# Generated by Django 4.0 on 2022-04-05 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя категории')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('is_availability', models.BooleanField(default=False, verbose_name='Доступность')),
                ('quantity', models.IntegerField(default=0, verbose_name='Кол-во в наличии')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_name', models.CharField(max_length=255, verbose_name='Транспортная компания')),
            ],
            options={
                'verbose_name': 'Транспортная компания',
                'verbose_name_plural': 'Транспортная компании',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя производителя')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('logo', models.ImageField(upload_to='photos/manufacturer/%Y/%m/%d', verbose_name='Лого')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=255, verbose_name='Платёжная система')),
            ],
            options={
                'verbose_name': 'Платёжная система',
                'verbose_name_plural': 'Платёжная системы',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Этап доставки')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя товара')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='photos/product/%Y/%m/%d', verbose_name='Изображение')),
                ('model', models.CharField(max_length=255, verbose_name='Модель товара')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('is_availability', models.BooleanField(default=False, verbose_name='Доступность')),
                ('quantity', models.IntegerField(default=0, verbose_name='Кол-во в наличии')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория')),
                ('manuf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_price', models.FloatField(verbose_name='Цена всего заказа')),
                ('comment', models.TextField(blank=True, verbose_name='Описание')),
                ('amount', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer', verbose_name='Покупатель')),
                ('delivery_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.deliverymethod', verbose_name='Способ доставки')),
                ('delivery_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.status', verbose_name='Статус доставки')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.paymentmethod', verbose_name='Способ оплаты')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
