# Generated by Django 4.0 on 2022-04-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_deliverymethod_manufacturer_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='1', max_length=255, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='slug',
            field=models.SlugField(default='1', max_length=255, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(default='1', max_length=255, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='1', max_length=255, verbose_name='URL'),
        ),
    ]
