# Generated by Django 4.0 on 2022-04-11 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_slug_alter_manufacturer_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manuf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.manufacturer', verbose_name='Производитель'),
        ),
    ]
